# Generated by Django 5.1.7 on 2026-09-19 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('sort', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.CharField(db_index=True, max_length=64)),
                ('client_name', models.CharField(max_length=200)),
                ('day', models.DateField(db_index=True)),
                ('start_min', models.IntegerField()),
                ('end_min', models.IntegerField()),
                ('status', models.CharField(default='confirmed', max_length=24)),
                ('comment', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='app', max_length=24)),
                ('prepay_required', models.IntegerField(default=0)),
                ('prepay_paid', models.IntegerField(default=0)),
                ('hold_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('admin_note', models.TextField(blank=True, default='')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CareCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('telegram_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default='', max_length=64)),
                ('first_name', models.CharField(default='Гость', max_length=120)),
                ('last_name', models.CharField(blank=True, default='', max_length=120)),
                ('role', models.CharField(default='client', max_length=16)),
                ('intake', models.JSONField(default=dict)),
                ('intake_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DayHours',
            fields=[
                ('day', models.DateField(primary_key=True, serialize=False)),
                ('start_min', models.IntegerField()),
                ('end_min', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loyalty',
            fields=[
                ('client_key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('stamps', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('appointment_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OpenDay',
            fields=[
                ('day', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(default='', max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_min', models.IntegerField()),
                ('price', models.IntegerField()),
                ('prepay_amount', models.IntegerField(default=0)),
                ('prepay_percent', models.IntegerField(default=0)),
                ('prep_text', models.TextField(blank=True, default='')),
                ('aftercare_text', models.TextField(blank=True, default='')),
                ('indications', models.TextField(blank=True, default='')),
                ('contraindications', models.TextField(blank=True, default='')),
                ('result_text', models.TextField(blank=True, default='')),
                ('reactions_text', models.TextField(blank=True, default='')),
                ('image_key', models.CharField(default='still', max_length=40)),
                ('invasive', models.BooleanField(default=False)),
                ('recommend_days', models.IntegerField(default=90)),
                ('sort', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_min', models.IntegerField(default=0)),
                ('end_min', models.IntegerField(default=1440)),
                ('reason', models.CharField(default='Выходной', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CareProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('indications', models.TextField(blank=True, default='')),
                ('contraindications', models.TextField(blank=True, default='')),
                ('composition', models.TextField(blank=True, default='')),
                ('price', models.IntegerField(default=0)),
                ('photo', models.CharField(blank=True, default='', max_length=300)),
                ('sort', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clinic.carecategory')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.CharField(max_length=64)),
                ('rating', models.IntegerField()),
                ('text', models.TextField(blank=True, default='')),
                ('photos', models.TextField(default='[]')),
                ('service_title', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinic.appointment')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.service'),
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.CharField(max_length=64)),
                ('client_name', models.CharField(max_length=200)),
                ('desired_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.service')),
            ],
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['day', 'status'], name='clinic_appo_day_6f099a_idx'),
        ),
    ]
